#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$ROOT/tools/modkit.py"

if [ ! -f "$TARGET" ]; then
    echo "winnative_modkit_love: $TARGET not found" >&2
    exit 1
fi

python3 - "$TARGET" <<'PY'
import sys

path = sys.argv[1]
anchor = (
    'DRIVER_TEMPLATE = """-- generated by tools/modkit.py; '
    'drives the real loader headlessly\n'
    'package.path = "./?.lua;./?/init.lua;" .. package.path\n'
)
inject = anchor + 'if not _G.love then _G.love = require("tests.love_stub") end\n'

src = open(path, encoding="utf-8").read()

if inject in src:
    print("winnative_modkit_love: already applied")
    raise SystemExit(0)

found = src.count(anchor)
if found != 1:
    print(
        "winnative_modkit_love: expected one DRIVER_TEMPLATE header, found "
        f"{found}; upstream moved it, refusing to patch",
        file=sys.stderr,
    )
    raise SystemExit(1)

open(path, "w", encoding="utf-8").write(src.replace(anchor, inject))
print("winnative_modkit_love: gave the validate driver a headless love")
PY
